name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 1,11,21 * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync upstream changes
        id: sync
        uses: aormsby/fork-sync-actions@v3.4
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: 7Sageer/sublink-worker
          test_mode: false
          upstream_pull_args: '--allow-unrelated-histories -Xtheirs'
